name: ci-test
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "install dependencies"
        run: |
          yarn
      - name: "setup node"
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: "eslint"
        run: |
         yarn build-ts   
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist