name: ci-test
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
        with:
          persist-credentials: false 
          fetch-depth: 0
      - name: "install dependencies"
        run: |
          yarn
      - name: "setup node"
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: "eslint"
        run: |
         yarn build-ts   
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist
      - name: "rebuild dist folder for dist branch"
        run: |
          git branch --delete --force dist || true
          git checkout --orphan dist
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@github.com"
          git add -f dist
          git commit -m "Rebuild dist folder [github-ci]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        env:
            INPUT_GITHUB_TOKEN: ${{ secrets.ARNFT_TOKEN }}
        with:
          branch: dist
          force: true
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.8
        with: # All of theses inputs are optional
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          commit_pattern: "^Release (\\S+)"
          workspace: "."
          publish_command: "yarn"
          publish_args: "--non-interactive"
        env: # More info about the environment variables in the README
          GITHUB_TOKEN: ${{ secrets.ARNFT_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.ARNFT_TOKEN }} # You need to set this in your repo settings
